general:
  dimensions: 2
  random_bool: false
  seed_id: 2907
grid:
  loc_hp:
  - 50
  - 120
  - 1
  ncells:
  - 20
  - 256
  - 1
  size:
  - 100
  - 1280
  - 5.0
permeability:
  case: perlin_v2
  factor: 40
  frequency:
  - 9
  - 9
  perm_max: 5.09683995922528e-09
  perm_min: 1.0193679918450561e-11
